# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saahil's website!
email: saahil.aneja@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This is the website of Saahil Aneja, a seventh grader! Coded using Github, Codecademy, and the domain from Amazon, I am looking forward to updating this site! 
baseurl: "/About"
baseurl: "/Saahilisms" # the subpath of your site, e.g. /blog
baseurl: "/Sports"
baseurl: "/Music"
baseurl: "/Academics"
baseurl: "/Fun"
url: "http://saahilaneja.com" # the base hostname & protocol for your site

github_username: Saneja
codecademy_username: Saneja

# Build settings
markdown: kramdown
