# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saahil's website!
email: saahil.aneja@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Welcome to my site! 
baseurl: ""
url: "http://saahilaneja.com" # the base hostname & protocol for your site

github_username: Saneja
codecademy_username: Saneja

# Build settings
markdown: kramdown

